version: "2"
services:
  http:
    image: nginx
    environment:
      - VIRTUAL_HOST=loa.dev
    volumes:
      - ./provision/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./provision/nginx/conf.d:/etc/nginx/conf.d
      - ./provision/nginx/sites-enabled-dev:/etc/nginx/sites-enabled
      - ./public:/opt/web
    networks:
      - default
      - proxy_default

  app:
    image: kendu/php:7.0
    volumes:
      - ./provision/php/dev/php-fpm.conf:/etc/php/7.0/fpm/php-fpm.conf
      - ./provision/php/dev/pool.conf:/etc/php/7.0/fpm/pool.d/www.conf
      - ./provision/php/dev/php.ini:/etc/php/7.0/fpm/conf.d/99.custom.ini
      - .:/opt/web
    networks:
      - default
      - loa_default

  db:
      image: postgres
      environment:
        - POSTGRES_PASSWORD=loa
        - POSTGRES_USER=loa
        - POSTGRES_DB=loa
      ports:
        - "0.0.0.0:5431:5430"
      networks:
        - default

networks:
  proxy_default:
    external:
      name: proxy_default
  loa_default:
    external:
      name: loa_default
